### ISSUE TITLE
Angular 8 example with signup form

### ISSUE THREAD

**Issue by ultrasonicsoft** [rough-stuff/wired-elements#106]
Hi Team,

I have seen the Angular example on your official website which is very simple and I thought to create a bit more feature rich example. Hence created an Angular 8 application using WiredJs component and published blog on the same.

Please include in your example list if you find it interesting.

Source code:
https://github.com/ultrasonicsoft/ng-wiredjs-demo

Demo: 
http://ng-wiredjs-demo.surge.sh/

Blog:
https://medium.com/@balramchavan/wireframe-sketched-angular-v8-application-3bc48d8cae2d

Thanks!

-
Balram

**Comment by pshihn** [comment]
Thanks! Will add this

**Comment by TechRova** [comment]
> Hi Team,
> 
> I have seen the Angular example on your official website which is very simple and I thought to create a bit more feature rich example. Hence created an Angular 8 application using WiredJs component and published blog on the same.
> 
> Please include in your example list if you find it interesting.
> 
> Source code:
> https://github.com/ultrasonicsoft/ng-wiredjs-demo
> 
> Demo:
> http://ng-wiredjs-demo.surge.sh/
> 
> Blog:
> https://medium.com/@balramchavan/wireframe-sketched-angular-v8-application-3bc48d8cae2d
> 
> Thanks!
> 
> 
> Balram

Also use handwritting fonts please , so it looks more natural
