### ISSUE TITLE
The components do not scale to its content

### ISSUE THREAD

**Issue by Tumulte** [rough-stuff/wired-elements#107]
I've tried to use wired, but the box is off (like a -10px margin), and it doesn't scale to a large content.

I've tried to add a long text to the demo page and end up with the same problem

Is there a way to solve that ?

**Comment by pshihn** [comment]
Usually you can call `.requestUpdate()` on the element to re-render. 
If you can publish a sample on jsbin or something like that, it would be easier to identify the specific issue. Thanks
