### ISSUE TITLE
Using with Create-React-App and TypeScript

### ISSUE THREAD

**Issue by jameshschuler** [rough-stuff/wired-elements#117]
Has anyone been able to get this working with Create-React-App and TypeScript? Seem to be just getting these errors 

> Property 'wired-button' does not exist on type 'JSX.IntrinsicElements'.

> JSX element type 'WiredButton' is not a constructor function for JSX elements.
>   Type 'WiredButton' is missing the following properties from type 'ElementClass': context, setState, forceUpdate, props, and 2 more.ts(2605)

**Comment by pshihn** [comment]
I haven't but if you have a repo to share, I can take a look.

**Comment by jameshschuler** [comment]
Here's the repo https://github.com/jameshschuler/HomeDoneGames/tree/master/PoolHouseStudio.HomeDoneGames.GameManager and the specific file I was trying
https://github.com/jameshschuler/HomeDoneGames/blob/master/PoolHouseStudio.HomeDoneGames.GameManager/src/components/Navbar.tsx

**Comment by haikyuu** [comment]
The sandbox example in the readme isn't working either

**Comment by lvandernoll** [comment]
What fixed this for me is adding this at the bottom of `src/index.tsx`:
```ts
declare global {
  namespace JSX {
    interface IntrinsicElements {
      'wired-card': any,
      'wired-button': any,
      'wired-image': any,
    }
  }
}
```
And then add all components you wish to use

**Comment by apennamen** [comment]
@haikyuu indeed the link on the sandbox in index.html should be changed to:
```html
    <script
      async
      src="https://unpkg.com/wired-elements@latest/lib/wired-elements-bundled.js"
    ></script>
```

@lvandernoll seems to be the best way to handle it:
https://wespeter.com/posts/consuming-web-component-react-typescript/
According to [TypeScript documentation](https://www.typescriptlang.org/docs/handbook/jsx.html#intrinsic-elements), you can also use a "catch them all" solution with:
```typescript
declare namespace JSX {
    interface IntrinsicElements {
        [elemName: string]: any;
    }
}
```

IMO there's nothing that can be done on the side of the wired components.
One last thing to test, even if not directly linked to the issue, is to convert the webcomponent to react component using this: https://github.com/webcomponents/react-integration

Regards

**Comment by jameshschuler** [comment]
Thanks for all the help! I'll have to give it another try as soon as I get the chance.

**Comment by pshihn** [comment]
Also React Sandbox updated in readme and website: https://codesandbox.io/s/xrll5wyl8w

**Comment by alexandrtovmach** [comment]
More accurate typings for each element: https://github.com/rough-stuff/wired-elements/issues/68#issuecomment-1334530611
