### ISSUE TITLE
Unable to define height of Tabs container

### ISSUE THREAD

**Issue by mrosi** [rough-stuff/wired-elements#120]
Hi, I have found that body of each Tab has own height. I've tried to align it to fill parent container but without success. Do you have any solution?
Thanks a lot

**Comment by pshihn** [comment]
You can do that by setting the height of <wired-tab> to be whatever you want. 
e.g here. https://codesandbox.io/s/keen-clarke-ge7zk?file=/index.html where height is set to 50vh; 
You could set it to 100% of container for positioned elements
