### ISSUE TITLE
wired-slider value attribute not updating

### ISSUE THREAD

**Issue by MarcSkovMadsen** [rough-stuff/wired-elements#121]
#### My Pain

I'm trying to use the wired elements and I'm having problems with the `wired-slider` because it does not react correctly to the `value` attribute.

I would expect the slider visually to be at beginning in both examples shown below

![image](https://user-images.githubusercontent.com/42288570/75623447-58c38d00-5baa-11ea-8b08-5aaee86d2c62.png)

#### Reproducible Example

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>title</title>
    <script src="https://unpkg.com/@webcomponents/webcomponentsjs@2.2.7/webcomponents-loader.js"></script>
    <script type="module" src="https://unpkg.com/wired-slider@2.0.0/lib/wired-slider.js?module"></script>
</head>

<body>
    <wired-slider id="slider" value="0" knobradius="15" class="wired-rendered" style="margin: 0px"></wired-slider>
    <br />
    <wired-slider knobradius="15" value="5" min="5" max="15"></wired-slider>
</body>

</html>
```

#### Is this a regression?

Yes. I have seen it working in previous versions.

**Comment by MarcSkovMadsen** [comment]
And if possible please make sure that the other attributes work as well.

And if possible it would be so nice if the attributes and properties of all the wired web components are in sync. 

For example right now you don't update the value attribute when the user drags the slider. Instead you only update some knob transform value. The great promise of web components is that you can use them via HTML only. I want to be able to control web components by setting and getting the html attributes only.

My use case is adding the wired components to Panel. Panel is a framework for creating awesome analytics apps in Python only. See https://github.com/holoviz/panel/pull/1122

**Comment by MarcSkovMadsen** [comment]
And please update `https://wiredjs.com/dist/showcase.min.js` when this has been fixed as this is the one i'm using normally.

**Comment by MarcSkovMadsen** [comment]
I've been able to find a work around for my use case. But I still believe it's important in general to solve.

**Comment by apennamen** [comment]
Hello,
I was able to reproduce, and I agree it has to be fixed. Seems to be a regression links to this commit:
https://github.com/wiredjs/wired-elements/commit/9b1b5460514b375b82ace962da58f9fc06f96c23#diff-9f5c646f774ca45f8639d095bf011f0f

I think method firstUpdated should be:
```javascript
firstUpdated() {
    this.value = this.pendingValue || +(this.getAttribute('value') || this.min);
    delete this.pendingValue;
}
```

instead of (actual):
```javascript
firstUpdated() {
    this.value = this.pendingValue || this.value || +(this.getAttribute('value') || this.min);
    delete this.pendingValue;
}
```

I've tested the slider element with the modified firstUpdated method and it works. I don't know if there are other impacts.

I can make a PR with this modification if wanted.

**Comment by apennamen** [comment]
I've tested the video component, I don't know what is the expected behaviour.
With the modification suggested previously, volume is at 100% when video begins.

@pshihn I wonder why all this complexity was added on the slider side for the video ?
