### ISSUE TITLE
wired-input not updating value property, value attribute and not firing onchange

### ISSUE THREAD

**Issue by MarcSkovMadsen** [rough-stuff/wired-elements#123]
#### My Pain

I'm trying to add support for the Wired Elements to Panel, a framework for creating awesome analytics apps in Python.

When using the `wired-input` and writing "abcde" + enter the following does not happen

1. The `value` attribute does not change
2. The `value` property does not change
3. The `onchange` event does not fire.

I would have expected 2. + 3. and maybe 1.

Instead I can see that the `textinput.value` changes

![image](https://user-images.githubusercontent.com/42288570/75951668-e35b0380-5eac-11ea-8ad8-01ce3909cc7d.png)

#### Solution

As a minimum update the `value` property. Consider fixing some of the other things as well.

#### Additional Context

Im using Wired by including

```html
<script src="https://unpkg.com/@webcomponents/webcomponentsjs@2.2.7/webcomponents-loader.js"></script>
<script src="https://wiredjs.com/dist/showcase.min.js"></script>
```

**Comment by MarcSkovMadsen** [comment]
I've been able to find a work around for my use case. But I still believe it's important in general to solve.

**Comment by pshihn** [comment]
I've tested this in v2.1.1 and both points 2 and 3 seem to have been fixed. 
Attribute not changing is by design. Like <input> value is not reflected to the attribute
