### ISSUE TITLE
wired-input doesnt render in slot (in wired-card)

### ISSUE THREAD

**Issue by martinKumhera** [rough-stuff/wired-elements#128]
If you define an element with a slot element within a wire-card and use this element and provide a wired-input element, it will not be shown.

**Comment by martinKumhera** [comment]
MyElement:
import { html, css, LitElement } from 'lit-element';

export class MyElement extends LitElement {
  static get styles() {
    return css`
      :host {
      }
    `;
  }

  static get properties() {
    return {
    };
  }

  constructor() {
    super();
  }

  render() {
    return html`
      <wired-card>
        <slot></slot>
      </wired-card>
    `;
  }
}

window.customElements.define('my-element', MyElement);

MyApp:
import { html, css, LitElement } from 'lit-element';
import { MyElement } from './MyElement.js';

export class MyApp extends LitElement {
  static get styles() {
    return css`
      :host {
      }
    `;
  }

  static get properties() {
    return {
    };
  }

  constructor() {
    super();
  }

  render() {
    return html`
      <my-element>
        <wired-input placeholder="Test" value="test"></wired-input>
      </my-element>
    `;
  }
}

window.customElements.define('my-app', MyApp);

**Comment by martinKumhera** [comment]
![myApp](https://user-images.githubusercontent.com/13984637/78119031-150dae80-7408-11ea-89e6-66d64c6192d5.png)

**Comment by pshihn** [comment]
This should be resolve in v2.1.2
