### ISSUE TITLE
framework demo links broken

### ISSUE THREAD

**Issue by rchod** [rough-stuff/wired-elements#130]
Hello @pshihn,

All the demo links containing a link to `https://unpkg.com/wired-elements@latest/dist/wired-elements.bundled.js
` are broken, if I change them to `https://unpkg.com/wired-elements@latest/lib/wired-elements-bundled.js` they work but maybe the dist folder should be present in the first place ?

![image](https://user-images.githubusercontent.com/623771/78462068-f2f98200-76ce-11ea-9873-659c58a7645c.png)

**Comment by pshihn** [comment]
Sorry about this. all demo links fixed.
