### ISSUE TITLE
"dist" directory referenced in readme does not exist

### ISSUE THREAD

**Issue by rroehl007** [rough-stuff/wired-elements#145]
The dist folder (https://github.com/wiredjs/wired-elements/tree/master/packages/all/dist) referenced in the readme no longer exists.

In a related issue, the sandbox set up by psshihn no longer works, for this same reason: https://codesandbox.io/s/p77jkn13nq?file=/index.html

If I edit the async script's src to "https://unpkg.com/wired-elements@latest", the sandbox then works.

Just FYI, thanks for this interesting and imaginative collection :-)

**Comment by pshihn** [comment]
Sorry I have updated the sandbox and other links. 
And sorry for being so slow at dealing with these issues
