### ISSUE TITLE
How can I open dialog dynamically?

### ISSUE THREAD

**Issue by merbin2012** [rough-stuff/wired-elements#148]
I am using jquery, and I want to know how to open the wired-dialog dynamically.

**Comment by pshihn** [comment]
In plain javascript you can get a reference to the dialog, and then set open to true:

```javascript
const dialog = document.querySelector('wired-dialog');
dialog.open = true;
```

**Comment by merbin2012** [comment]
Thank you very much @pshihn, due to the unknown, I removed this library from my projects using images instead.
