### ISSUE TITLE
React example broken

### ISSUE THREAD

**Issue by zxti** [rough-stuff/wired-elements#150]
This is the example codesandbox in the README:

https://codesandbox.io/embed/xrll5wyl8w

For me, it never loads, and I just see:

![Screen Shot 2020-06-18 at 12 47 59 AM](https://user-images.githubusercontent.com/44424944/84992955-771fab00-b0fd-11ea-97a0-a014af0fdfd7.png)

**Comment by pshihn** [comment]
Fixed: https://codesandbox.io/s/xrll5wyl8w
