### ISSUE TITLE
WiredSlicer documentation mention knobradius attribute that does not work

### ISSUE THREAD

**Issue by titimoby** [rough-stuff/wired-elements#153]
I was trying to modify the radius of the knob on a slider and nothing happend.
As mentioned in the [doc](packages/wired-slider/README.md) I used all attributes:

> <wired-slider knobradius="15" value="10" min="5" max="15"></wired-slider>

But whatever the value I give to knobradius, no visible changes in my app.
I looked at the code, and there seems to be no such attribute.

**Comment by pshihn** [comment]
docs fixed
