### ISSUE TITLE
Request for Paginated table

### ISSUE THREAD

**Issue by dosindi** [rough-stuff/wired-elements#67]
The element looks great for web project. Mine isn't an issue is more of a request for a paginated Table.

**Comment by pshihn** [comment]
Can you elaborate more on what sort of table would you like?

**Comment by aadamsx** [comment]
Just a responsive regular table that paginates when the limit set on the properties is met to start I would think?  A grid/table would be amazing!

**Comment by pshihn** [comment]
I think pagination can be achieved externally, what it seems I need is a generic grid/table control
