### ISSUE TITLE
Design Resources

### ISSUE THREAD

**Issue by ridhoassuryadi** [rough-stuff/wired-elements#98]
Hi, thanks for to make great web components. I want to create a project, but before I wanna custom some element and create a layout using these web components. so can i get like (sketch.files / figma.files ) ?.

**Comment by pshihn** [comment]
Sorry, I do't have any or know how to. Contributions welcome.
Resources could probably be created from https://wiredjs.com/showcase.html

**Comment by muhammadridho** [comment]
can you tell me, where i put when i made that resource ?

**Comment by pshihn** [comment]
storybook should work for this
