### ISSUE TITLE
wired-tabs with nested wired-elements not working properly

### ISSUE THREAD

**Issue by abar193** [rough-stuff/wired-elements#99]
if you put some wired-element (tested with button and tabs) inside of wired-tabs then any element, located not on initially active tab won't be rendered properly (e.g. buttons won't have their borders, e.t.c.)

An example here: https://codesandbox.io/s/48l9592k9x

**Comment by pshihn** [comment]
Ah yeah. Some background around this:
Wired elements need to know their size to draw sketchy lines around them. 
When not visible the size is not available. 
As a work around you can call `requestUpdate()` method on the buttons when tab is visible. 
I know this is not a viable workaround - will resolve this properly soon.

**Comment by pshihn** [comment]
Dev note: Perhaps add a trigger to parse down the tree to re-render

**Comment by constantine71** [comment]
same issue when use them in react app created by create-react-app
I was trying to put a wired-link inside a wired-card
then the wired-link would not show at all
`import React from "react";
import "wired-card";
import "wired-link";
const Home = () => {
  return (
    <div>
      <wired-link>askjdhakjshdkjash</wired-link>
      <wired-card>
        this is wired card
        <wired-link>this is wired link</wired-link>
      </wired-card>
    </div>
  );
};

export default Home;
`

**Comment by constantine71** [comment]
same issue when use them in my react app created by create-react-app
I was trying to put a wired-link inside a wired-card
then the wired-link would not show at all
<wired-card>
        this is a wired card
        <wired-link>this is a wired link</wired-link>
</wired-card>

**Comment by pshihn** [comment]
resolved in 2.1.2
